# Generated by Django 3.2.9 on 2021-11-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
